package formularios;

import classes.Dados;
import classes.Opcoes;
import classes.Utilidades;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndersoNMN
 */
public class frmFaturamento extends javax.swing.JInternalFrame {
    
    private Dados msDados;
    private DefaultTableModel mTablela; 
    
    public void setDados(Dados msDados) {
        this.msDados = msDados;
    }

    /**
     * Creates new form frmFaturamento
     */
    public frmFaturamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtQuanti = new javax.swing.JTextField();
        cmbProduto = new javax.swing.JComboBox<>();
        cmbCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalhesVenda = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtValorTot = new javax.swing.JTextField();
        txtQuantTot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnExvaziar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisarProd = new javax.swing.JButton();
        bntPesquisarClient = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Formulario de Venda");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Cliente");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Produto");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Quantidade");

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtData.setEnabled(false);

        txtQuanti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblDetalhesVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalhesVenda);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Total");

        txtValorTot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtValorTot.setEnabled(false);

        txtQuantTot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuantTot.setEnabled(false);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N

        btnSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-adicionar-arquivo-36.png"))); // NOI18N
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-remove-properties-36.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnExvaziar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancelar-assinatura-36.png"))); // NOI18N
        btnExvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExvaziarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-salvar-e-fechar-36.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesquisarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pesquisar-36.png"))); // NOI18N
        btnPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdActionPerformed(evt);
            }
        });

        bntPesquisarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pesquisar-36.png"))); // NOI18N
        bntPesquisarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(txtQuantTot, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(txtValorTot, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(48, 48, 48)
                                        .addComponent(cmbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSalva)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnExcluir)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnExvaziar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSalvar))
                                            .addComponent(txtQuanti, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtData))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPesquisarProd)
                                    .addComponent(bntPesquisarClient))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntPesquisarClient)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarProd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtQuanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalva)
                            .addComponent(btnExcluir)
                            .addComponent(btnExvaziar)
                            .addComponent(btnSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Opcoes opc = new Opcoes("andersonmoura812@gmail.com", "Selecione um cliente");
        cmbCliente.addItem(opc.toString());
        for (int i = 0; i<msDados.numeroClientes(); i++) {
            opc = new Opcoes(
                  msDados.getClientes()[i].getIdCliente(),
                  msDados.getClientes()[i].getNome() +""+
                  msDados.getClientes()[i].getSobreNome());
                  cmbCliente.addItem(opc.toString());
        }
        
        
        opc = new Opcoes("andersonmoura812@gmail.com", "Selecione um Produto");
        cmbProduto.addItem(opc.toString());
        for (int i = 0; i<msDados.numeroProdutos(); i++) {
            opc = new Opcoes(
                  msDados.getProdutos()[i].getIdProduto(),
                  msDados.getProdutos()[i].getDescircao());
                  cmbProduto.addItem(opc.toString());
        }
        txtData.setText(Utilidades.getDate());
        
        preencherTabelaVenda();
    }//GEN-LAST:event_formInternalFrameOpened

        
        
    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        // validaçoes para adicionar os produtos ao formulario
        if(cmbProduto.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane,"Selecionar um PRODUTO");
            cmbProduto.requestFocusInWindow();
            return;
        }
        
        if(txtQuanti.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Selecionar uma Quantidade");
            cmbProduto.requestFocusInWindow();
            return;
        }
        
        if (!Utilidades.isNumeric(txtQuanti.getText())) {
            JOptionPane.showMessageDialog(rootPane,"Favor Digitar somente numeros.");
            txtQuanti.setText("");
            txtQuanti.requestFocusInWindow();
            return;
        }
        
        int quantidade = Integer.parseInt(txtQuanti.getText());
        if (quantidade <= 0){
            JOptionPane.showMessageDialog(rootPane,"Favor Digitar um numero acima de zero.");
            txtQuanti.setText("");
            txtQuanti.requestFocusInWindow();
            return;
        }
        
        // voltar aqui para RESOLVER O ERRO!!!!!  (Problema resolvido com ganbiarra, coloquei para selecionar pelo index no combo box em vez de selecionar pelo valor do prod)
        // A pessoa tem que colocar os id do prod na ordem crescente se n da ruim
        var cmbProd = cmbProduto.getSelectedIndex();
        //System.out.println( cmbProd + "formularios.frmFaturamento.btnSalvaActionPerformed()");
        int pos; // metodo para pegar o produto de acordo com a posição dele;
        pos = msDados.posicaoProduto(""+cmbProd);
        
        
        //Preenche com os valores escolhidos
        String registro[] = new String[5];
        registro[0] = msDados.getProdutos()[pos].getIdProduto();
        registro[1] = msDados.getProdutos()[pos].getDescircao();
        registro[2] = "" + msDados.getProdutos()[pos].getPreco();
        registro[3] = "" + quantidade;
        registro[4] = "" + (quantidade * msDados.getProdutos()[pos].getPreco());
        mTablela.addRow(registro);
        
        cmbProduto.setSelectedIndex(0);
        txtQuanti.setText("");
        cmbProduto.requestFocusInWindow();
        totais();
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(cmbCliente.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(rootPane,"Favor Selecionar um cliente!");
            cmbCliente.requestFocusInWindow();
            return;
        }
        
        if(txtQuantTot.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane,"Favor adicionar um Produto para Salvar");
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realizar a venda?");
        if (resposta != 0) {
            return;
        }
        
        int numFatura = msDados.getNumeroFatura()+1;
        
        FileWriter fw = null;
        PrintWriter pw = null;
            try {
                fw = new FileWriter("Data/Fatura.txt", true);
                pw = new PrintWriter(fw);
                
                var opcItemVal = (cmbCliente.getSelectedItem().toString());
                //System.out.println("360 ---->" + opcItemVal);
                
                var auxiliar = "1|"
                        +numFatura + "|"
                        +opcItemVal +"|"
                        +txtData.getText();
                
                
                pw.println("----------------------------");                      
                pw.println(auxiliar);
                pw.println("----------------------------");
             
                
            int num = tblDetalhesVenda.getRowCount();
            
            for (int i = 0; i<num; i++) {
                auxiliar = "2|"
                    + Utilidades.objectToString(tblDetalhesVenda.getValueAt(i, 0))+"|"
                    + Utilidades.objectToString(tblDetalhesVenda.getValueAt(i, 1))+"|"
                    + Utilidades.objectToString(tblDetalhesVenda.getValueAt(i, 2))+"|"
                    + Utilidades.objectToString(tblDetalhesVenda.getValueAt(i, 3))+"|"
                    + Utilidades.objectToString(tblDetalhesVenda.getValueAt(i, 4));
                
                pw.println(auxiliar);
            }
        

            } catch (Exception e1) {
                e1.printStackTrace();
                
            } finally{
                try {
                    if(fw != null) {
                        fw.close();
                    }
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
            }
            
            JOptionPane.showMessageDialog(rootPane,"Venda " + numFatura+ " REALIZADA COM SUCESSO!");
            msDados.setNumeroFatura(numFatura);
            cmbCliente.setSelectedIndex(0);
            limparTablea();
            totais();
            cmbCliente.requestFocusInWindow();
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExvaziarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente Deletar esta VENDA?");
                if (resposta != 0) {
                    return;
                }
            limparTablea();
            totais();
    }//GEN-LAST:event_btnExvaziarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(cmbProduto.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane,"Selecionar um PRODUTO");
            cmbProduto.requestFocusInWindow();
            return;
        }
        
        try {
            DefaultTableModel modelo = (DefaultTableModel)tblDetalhesVenda.getModel();
            int Linha = tblDetalhesVenda.getRowCount();
            for(int i = 0; Linha> i; i++){
                String idTabela = Utilidades.objectToString(tblDetalhesVenda.getValueAt(i, 0));
                var idCmb = cmbProduto.getSelectedIndex();
                if(idTabela.equals(""+idCmb)){
                    modelo.removeRow(i);
                    totais();
                    return;
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void bntPesquisarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarClientActionPerformed
        frmPesqClient mPesqCliente;
        mPesqCliente = new frmPesqClient(null, closable);
        mPesqCliente.setDados(msDados);
        mPesqCliente.setLocationRelativeTo(null);
        mPesqCliente.setVisible(true);
        String rta = mPesqCliente.getResposta();
        if(rta.equals("")){
            return;
        }
//        for(int i =0; i<cmbCliente.getItemCount(); i++) {;
//            if(((Opcoes)cmbCliente.getItemAt(i)).getValor().equals(rta)){
//                cmbCliente.setSelectedIndex(i);
//                return;
//            }
//        }
    }//GEN-LAST:event_bntPesquisarClientActionPerformed

    private void btnPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdActionPerformed
                frmPesqProd mPesqProduto;
                mPesqProduto = new frmPesqProd(null, closable);
                mPesqProduto.setDados(msDados);
                mPesqProduto.setLocationRelativeTo(null);
                mPesqProduto.setVisible(true);
                String rta = mPesqProduto.getResposta();
                if(rta.equals("")){
                    return;
                }
        //        for(int i =0; i<cmbProduto.getItemCount(); i++) {;
        //            if(((Opcoes)cmbProduto.getItemAt(i)).getValor().equals(rta)){
        //                cmbProduto.setSelectedIndex(i);
        //                return;
        //            }
        //        }
            
    }//GEN-LAST:event_btnPesquisarProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPesquisarClient;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExvaziar;
    private javax.swing.JButton btnPesquisarProd;
    private javax.swing.JButton btnSalva;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalhesVenda;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtQuantTot;
    private javax.swing.JTextField txtQuanti;
    private javax.swing.JTextField txtValorTot;
    // End of variables declaration//GEN-END:variables
        

//Cria os titulos da tabela de venda 
    private void preencherTabelaVenda(){
        String titulos[] =  {"ID Produto", "Descrição", "Preço", "Quantidade", "Valor"};
        String registro[] = new String[5];
        mTablela = new DefaultTableModel(null, titulos);
        tblDetalhesVenda.setModel(mTablela);
        
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.RIGHT); // Metodo para alinha os item a direita
        tblDetalhesVenda.getColumnModel().getColumn(2).setCellRenderer(dtcr);
        tblDetalhesVenda.getColumnModel().getColumn(3).setCellRenderer(dtcr);
        tblDetalhesVenda.getColumnModel().getColumn(4).setCellRenderer(dtcr);
    }
    
    //Para fazer a soma do valor total e quantidade toda de produtos
    private void totais() {
        int num = tblDetalhesVenda.getRowCount();
        int somaQuant = 0, somaVal=0;
        for (int i = 0; i<num; i++) {
            somaQuant += Utilidades.objectToDouble(tblDetalhesVenda.getValueAt(i, 3));
            somaVal += Utilidades.objectToDouble(tblDetalhesVenda.getValueAt(i, 4));
        }
        txtQuantTot.setText("" + somaQuant);
        txtValorTot.setText("" + somaVal);
    }
    
    public void limparTablea(){
        try {
            DefaultTableModel modelo = (DefaultTableModel)tblDetalhesVenda.getModel();
            int Linha = tblDetalhesVenda.getRowCount();
            for(int i = 0; Linha> i; i++){
                modelo.removeRow(0);
            }
        } catch (Exception e) {
        }
    }
    
    
}


