/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formularios;

import classes.Dados;
import classes.Utilidades;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndersoNMN
 */
public class frmPesqClient extends javax.swing.JDialog {
    
    private Dados msDados;
        private DefaultTableModel mTablela; 
        private String resposta= "";

        public void setDados(Dados msDados) {
            this.msDados = msDados;
        }
        
        public String getResposta(){
            return  resposta;
        }
    /**
     * Creates new form frmPesqClient
     */
    public frmPesqClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(radioID);
        buttonGroup1.add(radioNome);
        buttonGroup1.add(radioSobreNome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        radioID = new javax.swing.JRadioButton();
        radioNome = new javax.swing.JRadioButton();
        radioSobreNome = new javax.swing.JRadioButton();
        txtPesqClient = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnCancelarPesq = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioID.setText("ID Cliente");
        radioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIDActionPerformed(evt);
            }
        });

        radioNome.setText("Nome Cliente");
        radioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNomeActionPerformed(evt);
            }
        });

        radioSobreNome.setText("Sobre Nome Cliente");
        radioSobreNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSobreNomeActionPerformed(evt);
            }
        });

        txtPesqClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqClientActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pesquisa-propriedade-36.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnCancelarPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancelar-assinatura-36.png"))); // NOI18N
        btnCancelarPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarPesq)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioNome)
                        .addGap(62, 62, 62)
                        .addComponent(radioSobreNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(txtPesqClient, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioID)
                    .addComponent(radioNome)
                    .addComponent(radioSobreNome))
                .addGap(18, 18, 18)
                .addComponent(txtPesqClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisar)
                    .addComponent(btnCancelarPesq))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIDActionPerformed
        txtPesqClient.setText("");
        txtPesqClient.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioIDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencherTabela();
        txtPesqClient.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void radioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNomeActionPerformed
        txtPesqClient.setText("");
        txtPesqClient.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioNomeActionPerformed

    private void radioSobreNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSobreNomeActionPerformed
        txtPesqClient.setText("");
        txtPesqClient.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioSobreNomeActionPerformed

    private void txtPesqClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqClientActionPerformed
        preencherTabela();
    }//GEN-LAST:event_txtPesqClientActionPerformed

    private void btnCancelarPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPesqActionPerformed
        resposta = "";
        dispose();
    }//GEN-LAST:event_btnCancelarPesqActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int num = tblCliente.getRowCount();
        if(num == 0){
            resposta = "";
            dispose();
            return;
        }
        for (int i = 0; i<num; i++) {
            if(tblCliente.isRowSelected(i)){
                resposta = Utilidades.objectToString(tblCliente.getValueAt(i, 0));
                dispose();
                return;    
            }
        }
         resposta = Utilidades.objectToString(tblCliente.getValueAt(0, 0));
         dispose();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesqClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesqClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesqClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesqClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesqClient dialog = new frmPesqClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
        private void preencherTabela(){
        String titulos[] =  {"ID Cliente", "Nome", "Sobre Nome", "Email"};
        String registro[] = new String[7];
        mTablela = new DefaultTableModel(null, titulos);
        // preenche a tabela de cliente se nenhum pesquisa tivert sido feita ainda
        if(txtPesqClient.getText().equals("")){
            for(int i =0; i < msDados.numeroClientes(); i++) {
                registro[0] = msDados.getClientes()[i].getIdCliente();
                registro[1] = msDados.getClientes()[i].getNome();
                registro[2] = msDados.getClientes()[i].getSobreNome();
                registro[3] = msDados.getClientes()[i].getEmail();
                mTablela.addRow(registro);
            } 
            tblCliente.setModel(mTablela);
            return;
        }
        // preenche a tabela se o inpute de radio nome for selecionado, a pessoa pode pesquisar de acordo com o nome
            if (radioNome.isSelected()){
                for(int i =0; i < msDados.numeroClientes(); i++) {
                 if(msDados.getClientes()[i].getNome().startsWith(txtPesqClient.getText())){
                      registro[0] = msDados.getClientes()[i].getIdCliente();
                      registro[1] = msDados.getClientes()[i].getNome();
                      registro[2] = msDados.getClientes()[i].getSobreNome();
                      registro[3] = msDados.getClientes()[i].getEmail();
                      mTablela.addRow(registro);

                 }
                }
            tblCliente.setModel(mTablela);
            return;
            }  
        // preenche a tabela se o inpute de radio SobreNome for selecionado, a pessoa pode pesquisar de acordo com o Sobre Nome
            if (radioSobreNome.isSelected()){
                for(int i =0; i < msDados.numeroClientes(); i++) {
                 if(msDados.getClientes()[i].getSobreNome().startsWith(txtPesqClient.getText())){
                      registro[0] = msDados.getClientes()[i].getIdCliente();
                      registro[1] = msDados.getClientes()[i].getNome();
                      registro[2] = msDados.getClientes()[i].getSobreNome();
                      registro[3] = msDados.getClientes()[i].getEmail();
                      mTablela.addRow(registro);

                 }
                }
            tblCliente.setModel(mTablela);
            return;
            }  
        // preenche a tabela se o inpute de radio IdCliente for selecionado, a pessoa pode pesquisar de acordo com o IdCliente   
            if (radioID.isSelected()){
                for(int i =0; i < msDados.numeroClientes(); i++) {
                 if(msDados.getClientes()[i].getIdCliente().startsWith(txtPesqClient.getText())){
                      registro[0] = msDados.getClientes()[i].getIdCliente();
                      registro[1] = msDados.getClientes()[i].getNome();
                      registro[2] = msDados.getClientes()[i].getSobreNome();
                      registro[3] = msDados.getClientes()[i].getEmail();
                      mTablela.addRow(registro);

                 }
                }
            tblCliente.setModel(mTablela);
            return;
            }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPesq;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioID;
    private javax.swing.JRadioButton radioNome;
    private javax.swing.JRadioButton radioSobreNome;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtPesqClient;
    // End of variables declaration//GEN-END:variables
}
