
package formularios;

import classes.Dados;
import classes.Utilidades;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndersoNMN
 */
public class frmPesqProd extends javax.swing.JDialog {
    
    private Dados msDados;
        private DefaultTableModel mTablela; 
        private String resposta= "";

        public void setDados(Dados msDados) {
            this.msDados = msDados;
        }
        
        public String getResposta(){
            return  resposta;
        }
    /**
     * Creates new form frmPesqClient
     */
    public frmPesqProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(radioID);
        buttonGroup1.add(radioDescricao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        radioID = new javax.swing.JRadioButton();
        radioDescricao = new javax.swing.JRadioButton();
        txtPesqProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnCancelarPesq = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioID.setText("ID Produto");
        radioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIDActionPerformed(evt);
            }
        });

        radioDescricao.setText("Descrição Produto");
        radioDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDescricaoActionPerformed(evt);
            }
        });

        txtPesqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqProdActionPerformed(evt);
            }
        });

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProd);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pesquisa-propriedade-36.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnCancelarPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancelar-assinatura-36.png"))); // NOI18N
        btnCancelarPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarPesq)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(txtPesqProd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioID)
                    .addComponent(radioDescricao))
                .addGap(18, 18, 18)
                .addComponent(txtPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisar)
                    .addComponent(btnCancelarPesq))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIDActionPerformed
        txtPesqProd.setText("");
        txtPesqProd.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioIDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencherTabela();
        txtPesqProd.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void radioDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDescricaoActionPerformed
        txtPesqProd.setText("");
        txtPesqProd.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioDescricaoActionPerformed

    private void txtPesqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqProdActionPerformed
        preencherTabela();
    }//GEN-LAST:event_txtPesqProdActionPerformed

    private void btnCancelarPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPesqActionPerformed
        resposta = "";
        dispose();
    }//GEN-LAST:event_btnCancelarPesqActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int num = tblProd.getRowCount();
        if(num == 0){
            resposta = "";
            dispose();
            return;
        }
        for (int i = 0; i<num; i++) {
            if(tblProd.isRowSelected(i)){
                resposta = Utilidades.objectToString(tblProd.getValueAt(i, 0));
                dispose();
                return;    
            }
        }
         resposta = Utilidades.objectToString(tblProd.getValueAt(0, 0));
         dispose();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesqProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesqProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesqProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesqProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesqProd dialog = new frmPesqProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
        private void preencherTabela(){
        String titulos[] =  {"ID Produto", "Descrição"};
        String registro[] = new String[2];
        mTablela = new DefaultTableModel(null, titulos);
        // preenche a tabela de cliente se nenhum pesquisa tivert sido feita ainda
        if(txtPesqProd.getText().equals("")){
            for(int i =0; i < msDados.numeroProdutos(); i++) {
                registro[0] = msDados.getProdutos()[i].getIdProduto();
                registro[1] = msDados.getProdutos()[i].getDescircao();
                mTablela.addRow(registro);
            } 
            tblProd.setModel(mTablela);
            return;
        }
        // preenche a tabela se o inpute de radio nome for selecionado, a pessoa pode pesquisar de acordo com o nome
            if (radioDescricao.isSelected()){
                for(int i =0; i < msDados.numeroProdutos(); i++) {
                 if(msDados.getProdutos()[i].getDescircao().startsWith(txtPesqProd.getText())){
                      registro[0] = msDados.getProdutos()[i].getIdProduto();
                      registro[1] = msDados.getProdutos()[i].getDescircao();
                      mTablela.addRow(registro);
                 }
                }
            tblProd.setModel(mTablela);
            return;
            }  
        
        // preenche a tabela se o inpute de radio IdCliente for selecionado, a pessoa pode pesquisar de acordo com o IdCliente   
            if (radioID.isSelected()){
                for(int i =0; i < msDados.numeroClientes(); i++) {
                 if(msDados.getProdutos()[i].getIdProduto().startsWith(txtPesqProd.getText())){
                      registro[0] = msDados.getProdutos()[i].getIdProduto();
                      registro[1] = msDados.getProdutos()[i].getDescircao();
                      mTablela.addRow(registro);

                 }
                }
            tblProd.setModel(mTablela);
            return;
            }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPesq;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioDescricao;
    private javax.swing.JRadioButton radioID;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField txtPesqProd;
    // End of variables declaration//GEN-END:variables
}
