/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formularios;

/**
 *
 * @author AndersoNMN
 */
public class test extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRefriger = new javax.swing.JPanel();
        btnPizza4 = new javax.swing.JButton();
        btnPizza8 = new javax.swing.JButton();
        btnPizza9 = new javax.swing.JButton();
        btnPizza10 = new javax.swing.JButton();
        btnPizza11 = new javax.swing.JButton();
        btnPizza12 = new javax.swing.JButton();
        panelPizza = new javax.swing.JPanel();
        btnPizza3 = new javax.swing.JButton();
        btnPizza1 = new javax.swing.JButton();
        btnPizza2 = new javax.swing.JButton();
        btnPizza5 = new javax.swing.JButton();
        btnPizza7 = new javax.swing.JButton();
        btnPizza6 = new javax.swing.JButton();

        panelRefriger.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRefriger.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                panelRefrigerComponentRemoved(evt);
            }
        });
        panelRefriger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPizza4.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-soda-can-40.png"))); // NOI18N
        btnPizza4.setText("Refrigerante");
        btnPizza4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPizza4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizza4ActionPerformed(evt);
            }
        });
        panelRefriger.add(btnPizza4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 40, 110, 70));

        btnPizza8.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-soda-can-40.png"))); // NOI18N
        btnPizza8.setText("Refrigerante");
        btnPizza8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelRefriger.add(btnPizza8, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 116, 110, 70));

        btnPizza9.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-soda-can-40.png"))); // NOI18N
        btnPizza9.setText("Refrigerante");
        btnPizza9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelRefriger.add(btnPizza9, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 192, 110, 70));

        btnPizza10.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-soda-can-40.png"))); // NOI18N
        btnPizza10.setText("Refrigerante");
        btnPizza10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelRefriger.add(btnPizza10, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 192, 110, 70));

        btnPizza11.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-soda-can-40.png"))); // NOI18N
        btnPizza11.setText("Refrigerante");
        btnPizza11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelRefriger.add(btnPizza11, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 40, 110, 70));

        btnPizza12.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-soda-can-40.png"))); // NOI18N
        btnPizza12.setText("Refrigerante");
        btnPizza12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelRefriger.add(btnPizza12, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 116, 110, 70));

        panelPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPizza.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                panelPizzaComponentRemoved(evt);
            }
        });
        panelPizza.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPizza3.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-40.png"))); // NOI18N
        btnPizza3.setText("Pizzas");
        btnPizza3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelPizza.add(btnPizza3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 116, 110, 70));

        btnPizza1.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-40.png"))); // NOI18N
        btnPizza1.setText("Pizzas");
        btnPizza1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPizza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizza1ActionPerformed(evt);
            }
        });
        panelPizza.add(btnPizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 40, 110, 70));

        btnPizza2.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-40.png"))); // NOI18N
        btnPizza2.setText("Pizzas");
        btnPizza2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelPizza.add(btnPizza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 192, 110, 70));

        btnPizza5.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-40.png"))); // NOI18N
        btnPizza5.setText("Pizzas");
        btnPizza5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelPizza.add(btnPizza5, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 192, 110, 70));

        btnPizza7.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-40.png"))); // NOI18N
        btnPizza7.setText("Pizzas");
        btnPizza7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelPizza.add(btnPizza7, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 116, 110, 70));

        btnPizza6.setBackground(new java.awt.Color(204, 204, 204));
        btnPizza6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pizza-40.png"))); // NOI18N
        btnPizza6.setText("Pizzas");
        btnPizza6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPizza6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelPizza.add(btnPizza6, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 40, 110, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(panelPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRefriger, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(567, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(panelPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRefriger, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPizza4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizza4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPizza4ActionPerformed

    private void panelRefrigerComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelRefrigerComponentRemoved

    }//GEN-LAST:event_panelRefrigerComponentRemoved

    private void btnPizza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizza1ActionPerformed

    }//GEN-LAST:event_btnPizza1ActionPerformed

    private void panelPizzaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelPizzaComponentRemoved

    }//GEN-LAST:event_panelPizzaComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPizza1;
    private javax.swing.JButton btnPizza10;
    private javax.swing.JButton btnPizza11;
    private javax.swing.JButton btnPizza12;
    private javax.swing.JButton btnPizza2;
    private javax.swing.JButton btnPizza3;
    javax.swing.JButton btnPizza4;
    private javax.swing.JButton btnPizza5;
    private javax.swing.JButton btnPizza6;
    private javax.swing.JButton btnPizza7;
    private javax.swing.JButton btnPizza8;
    private javax.swing.JButton btnPizza9;
    private javax.swing.JPanel panelPizza;
    private javax.swing.JPanel panelRefriger;
    // End of variables declaration//GEN-END:variables
}
